language: r
sudo: false
cache: packages
r_build_args: "--resave-data=best"
env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf --resave-data=best"
     - R_CHECK_ARGS="--as-cran"
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

r_github_packages: 
  - jimhester/covr
  - trinker/qdapTools
  - trinker/qdapRegex
  - trinker/qdapDictionaries
  - ropensci/gender

before_install:
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  
after_success:
  - Rscript -e 'covr::coveralls()'
  

install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
  - ./travis-tool.sh install_r_binary xml
  - ./travis-tool.sh install_r_binary gplots
  - ./travis-tool.sh install_r_binary rjava
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github trinker/qdapTools
  - ./travis-tool.sh install_github trinker/qdapRegex
  - ./travis-tool.sh install_github trinker/qdapDictionaries
  - ./travis-tool.sh github_package ropensci/gender
  - ./travis-tool.sh install_deps

