language: r
sudo: false
cache: packages
r_build_args: --compact-vignettes=gs+qpdf --resave-data=best
r_check_args: --as-cran
env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

r_github_packages: 
  - jimhester/covr
  - trinker/qdapTools
  - trinker/qdapRegex
  - trinker/qdapDictionaries
  - ropensci/gender

before_install:
  - sh -e /etc/init.d/xvfb start
  - tlmgr install index
  - sudo apt-get install texinfo  
  
after_success:
  - Rscript -e 'covr::coveralls()'


