language: r
sudo: false
cache: packages
r_build_args: "--resave-data=best"
env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf --resave-data=best"
     - R_CHECK_ARGS="--as-cran"
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

r_github_packages: 
  - jimhester/covr
  - trinker/qdapTools
  - trinker/qdapRegex
  - trinker/qdapDictionaries
  - ropensci/gender

before_install:
  - sh -e /etc/init.d/xvfb start
  - tlmgr install index
  
after_success:
  - Rscript -e 'covr::coveralls()'


